#!/usr/bin/env bash
#a Bash script that displays To infinity and beyond indefinitely.
while true
do	echo "To infinity and beyond" 
	trap "echo 'I am invincible!!!'" SIGTERM
	trap exit SIGKILL
	sleep 2

done
