#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code, and
#+ displays form apache-access.log file in highest to lowest occurences.
awk '{count[$1" "$9]++} END  { for (value in count) print"    " count[value] " " value }' apache-access.log |  sort -rn
