#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code, and
#+ displays form apache-access.log file in highest to lowest occurences.
awk '{print $1,$9}' apache-access.log | sort | uniq -c | sort -nr
