#!/usr/bin/env bash
# This script is displays the time for 12 hours and 59 minutes
echo "Hour: 0"
i=1
hour=1
while [ $i -le 60 ];
do
	if [ $i -eq 60 ]
	then
		if [ $hour -gt 12 ]
    	then
			break
		fi
		i=1
		echo "Hour: $hour"
		hour=$((hour+1))
	fi
		echo "$i"
		i=$((i+1))
done

